name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging
      - testing

jobs:
  build-and-push:
    environment: Production
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Pull the current latest image
        run: docker pull oukaasha/flask-app-test:latest || true
  
      - name: Tag the current latest image as old
        run: |
          docker tag oukaasha/flask-app-test:latest oukaasha/flask-app-test:${{ github.ref_name }} || true
          docker tag oukaasha/flask-app-test:latest oukaasha/flask-app-test:old || true
  
      - name: Push the old image
        run: docker push oukaasha/flask-app-test:old || true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: oukaasha/flask-app-test:${{ github.ref_name }},oukaasha/flask-app-test::latest
          context: .

    # - name: Deploy to Digital Ocean
    #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/testing'
    #   run: ssh -o StrictHostKeyChecking=no root@your_digital_ocean_server_ip "docker pull oukaasha/flask-app-test:${{ github.ref_name }} && docker run -d --name flask-app-test -p 80:80 oukaasha/flask-app-test:${{ github.ref_name }}"
    #   env:
    #     DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
